copy Ace.upk     *.upk.bak
copy Ace__Ch2.upk     *.upk.bak
copy Ace_A1.upk     *.upk.bak
copy Ace_A1_Ch2.upk     *.upk.bak
copy Ace_A1_Ch23.upk     *.upk.bak
copy Ace_A1_Ch2_Anim.upk     *.upk.bak
copy Ace_A2.upk     *.upk.bak
copy Ace_A2_Ch2.upk     *.upk.bak
copy Ace_A2_Lift.upk     *.upk.bak
copy Ace_B1.upk     *.upk.bak
copy Ace_B1_Ch123y_Static.upk     *.upk.bak
copy Ace_B1_Ch2.upk     *.upk.bak
copy Ace_B2.upk     *.upk.bak
copy Ace_B2_Ch2.upk     *.upk.bak
copy Anim_IC_Professor_Pyg_SF.upk     *.upk.bak
copy Bank_Large.upk     *.upk.bak
copy Bank_Large_ChC0.upk     *.upk.bak
copy Bank_Large_Cine_LargeBank_Intro.upk     *.upk.bak
copy Bank_Med_ChC0.upk     *.upk.bak
copy Bank_Small.upk     *.upk.bak
copy Bank_Small_ChC0.upk     *.upk.bak
copy Bank_Small_ChC2b.upk     *.upk.bak
copy BarkCharDef_AR_Bank_SF.upk     *.upk.bak
copy BarkCharDef_Pred_Thug_AR_DLC_SF.upk     *.upk.bak
copy BarkCharDef_Pred_Thug_CatDLC_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_CombatThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_CARS-CLONED_Militia-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_CARS-CopMale-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_CARS-RiotThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Gordon-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Gordon-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Gordon-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Militia-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Militia-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_GORDON-Militia-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Militia-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Militia-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Militia-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Militia-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Red_Hood-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Red_Hood-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Red_Hood-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_CHASES_CH3_PURSUIT-Red_Hood-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_COMBAT-CLONED_CombatThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_COMBAT-CLONED_CombatThug-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-CLONED_CombatThug-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-CLONED_CombatThug-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-Heavy_Armour_Thug-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-Heavy_Armour_Thug-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-Heavy_Armour_Thug-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT-Heavy_Armour_Thug-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-CLONED_Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-CLONED_Militia-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-CLONED_Militia-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-CLONED_Militia-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-CLONED_Militia-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Combat_Expert-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Combat_Expert-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Combat_Expert-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Combat_Expert-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Heavy_Armour_Militia-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Heavy_Armour_Militia-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Heavy_Armour_Militia-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_COMBAT_MILITIA-Heavy_Armour_Militia-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_ADAPTIVE_AI-Red_Hood-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_ADAPTIVE_AI-Red_Hood-LoadWithinPredVol_Militia-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-batgirl-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-harleyquinn-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_BANKS-CLONED_CombatThug-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_PRED_GEN-CLONED_CombatThug-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_PRED_GEN-CLONED_CombatThug-AlwaysLoaded-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_PRED_GEN-CLONED_CombatThug-LoadWithinPredVol_Gang-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_PRED_GEN-CLONED_CombatThug-LoadWithinPredVol_Gang-nightwing-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_AR_VOICESYNTH-Red_Hood-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_MAIN_CATWOMAN-CLONED_CombatThug-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_MAIN_CATWOMAN-CLONED_CombatThug-LoadWithinPredVol_Gang-any-ALL_SF.upk     *.upk.bak
copy BARKSET_DLC_RS_MAIN_CATWOMAN-CLONED_CombatThug-LoadWithinPredVol_Gang-catwoman-ALL_SF.upk     *.upk.bak
copy BARKSET_DRONE-Deathstroke-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_DRONE-Deathstroke-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_DRONE-Deathstroke-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_DRONE-Deathstroke-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_DRONE-Deathstroke-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_DRONE-Militia-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_DRONE-Militia-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_DRONE-Militia-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_DRONE-Militia-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_DRONE-Militia-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_DRONE-Red_Hood-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_DRONE-Red_Hood-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_DRONE-Red_Hood-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH01_S13_FORENSICS-Militia-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH01_S13_FORENSICS-Militia-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH01_S13_FORENSICS-Militia-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH03_S01_CITYZ-Gordon-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH03_S01_CITYZ-Gordon-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH03_S01_CITYZ-Gordon-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH04_S07_STAGG_A1-CLONED_Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH04_S07_STAGG_A1-Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH04_S07_STAGG_A1-Militia-LoadWithinPredVol_Militia-any-CH4_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH06_S07_FILM_B3-Albert_King-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH06_S07_FILM_B3-Albert_King-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH08_S08_HIDEOUT_A3-Red_Hood-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH08_S08_HIDEOUT_A3-Red_Hood-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH09_S03_CLOCKTOWER_PREDATOR-Scarecrow-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH09_S03_CLOCKTOWER_PREDATOR-Scarecrow-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH10_S03_JOKER_C1_CRIME_ALLEY-Joker-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH10_S03_JOKER_C1_CRIME_ALLEY-Joker-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH10_S05_JOKER_A1_WAREHOUSE-CLONED_CombatThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_MAIN_CH10_S05_JOKER_A1_WAREHOUSE-CLONED_CombatThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_OW_CHOPPERS-CopFemale-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_OW_CHOPPERS-CopMale-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_OW_MILITIA-Militia-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-HarleyThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-PenguinThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-PenguinThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-PenguinThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-RiotThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH7C_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_OW_THUG-TwoFaceThug-AlwaysLoaded-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH2_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH4_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH8_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH9A_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_Militia-LoadWithinPredVol_Militia-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_PRED-CLONED_TwoFaceThug-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Deathstroke-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Deathstroke-LoadWithinPredVol_Militia-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Harley_Quinn-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Harley_Quinn-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_PRED-Militia-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_PRED-Militia-LoadWithinPredVol_Militia-any-CH2_SF.upk     *.upk.bak
copy BARKSET_PRED-Militia-LoadWithinPredVol_Militia-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-LoadWithinPredVol_Militia-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Red_Hood-LoadWithinPredVol_Militia-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_PRED-Two_Face-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED-Two_Face-LoadWithinPredVol_Gang-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-AlwaysLoaded-robin-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-LoadWithinPredVol_Gang-any-ALL_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-LoadWithinPredVol_Gang-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-LoadWithinPredVol_Gang-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-LoadWithinPredVol_Gang-any-CH6_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CLONED_CombatThug-LoadWithinPredVol_Gang-any-CH9C_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CombatThug_1_NonCloned-LoadWithinPredVol_Gang-any-CH6_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CombatThug_3_NonCloned-LoadWithinPredVol_Gang-any-CH6_SF.upk     *.upk.bak
copy BARKSET_PRED_T-CombatThug_4_NonCloned-LoadWithinPredVol_Gang-any-CH6_SF.upk     *.upk.bak
copy BARKSET_PRED_T-PenguinThug-LoadWithinPredVol_Gang-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_RIDDLER-Riddler-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH1A_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH1B_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH1C_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH2_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH3A_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH3B_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH3C_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH3D_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH4_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH5A_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH5B_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH5C_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH6_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH7A_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH7B_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH7D_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH8_SF.upk     *.upk.bak
copy BARKSET_SCENES-Scarecrow-AlwaysLoaded-any-CH9B_SF.upk     *.upk.bak
copy BARKSET_SIDE-Firefly-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_SIDE-Pyg-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_SIDE-Two_Face-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BARKSET_VOICE-Harley_Quinn-AlwaysLoaded-any-ALL_SF.upk     *.upk.bak
copy BatEntry.upk     *.upk.bak
copy BatEntry__Benchmark_ChJ7_Bm.upk     *.upk.bak
copy BatEntry__City_Ch0_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch1bc_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch1bcd_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch1d_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch2_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3a_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3bc_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3c_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3cd_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch3d_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch4_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch56789abc_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch5_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch5b_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch5c6_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch5c_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch7_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch7a_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch7b_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch7c_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch8_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch9_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch9a_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch9b_LOD2.upk     *.upk.bak
copy BatEntry__City_Ch9bc_LOD2.upk     *.upk.bak
copy BatEntry__City_ChD1b_LOD2.upk     *.upk.bak
copy BatEntry__City_ChF478_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1a_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1b_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1c_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1d_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1e_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1f_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1g_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1h_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1i_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1j_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1k_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1l_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1m_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1n_LOD2.upk     *.upk.bak
copy BatEntry__City_ChW1o_LOD2.upk     *.upk.bak
copy BmGame.upk     *.upk.bak
copy Char_Batman_Misc_Cant_SF.upk     *.upk.bak
copy Char_Batman_Misc_No_Bmob_SF.upk     *.upk.bak
copy Chases_Gen_Bm_Losing_Truck_Tag_SF.upk     *.upk.bak
copy Chases_Gen_Bm_No_Batmobile_SF.upk     *.upk.bak
copy Chases_Gen_Bm_No_Call_Bmbl_Alt_SF.upk     *.upk.bak
copy Chases_Gen_Bm_No_Call_Bmbl_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Bm_Spotted_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Bm_Spotted_2nd_Driver_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Bm_Spotted_2nd_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Bmobile_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Bmobile_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Drive_Idles_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Peng_Radio_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Pre_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Pre_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Pthug_Lost_Bm_1st_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Pthug_No_Bm_Chat_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Pthug_No_Bm_Chat_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_2_Truck_Drive_Idlechat_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Bm_Spotted_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Bm_Spotted_2nd_Driver_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Bm_Spotted_2nd_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Bmobile_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Bmobile_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Drive_Idles_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Peng_Radio_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Pre_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Pre_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Pthug_Lost_Bm_1st_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Pthug_No_Bm_Chat_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Pthug_No_Bm_Chat_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_3_Truck_Drive_Idlechat_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Bm_Spotted_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Bm_Spotted_2nd_Driver_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Bm_Spotted_2nd_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Bmobile_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Bmobile_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Drive_Idles_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Peng_Radio_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Pre_Chase_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Pre_Chase_Os_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Pthug_Lost_Bm_1st_Conv_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Pthug_No_Bm_Chat_1st_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Pthug_No_Bm_Chat_SF.upk     *.upk.bak
copy Chases_Gen_Peng_Chase_4_Truck_Drive_Idlechat_SF.upk     *.upk.bak
copy CityX.upk     *.upk.bak
copy CityX_01_ChA4.upk     *.upk.bak
copy CityX_01_ChB67_LOD1.upk     *.upk.bak
copy CityX_01_ChB6_LOD1.upk     *.upk.bak
copy CityX_03_Ch3c.upk     *.upk.bak
copy CityX_03_Static_LOD1.upk     *.upk.bak
copy CityX_04_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityX_04_ChR79_LOD1.upk     *.upk.bak
copy CityX_04_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_05.upk     *.upk.bak
copy CityX_05_ChQ1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_05_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_06.upk     *.upk.bak
copy CityX_06_Ch3.upk     *.upk.bak
copy CityX_06_Ch3d_Anim.upk     *.upk.bak
copy CityX_06_Ch4.upk     *.upk.bak
copy CityX_06_ChD1ab_Ch789.upk     *.upk.bak
copy CityX_06_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityX_06_ChX1_Ch789_LOD1.upk     *.upk.bak
copy CityX_07_Ch3d.upk     *.upk.bak
copy CityX_07_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityX_07_Cine_Ch3d_Meet_Nightwing.upk     *.upk.bak
copy CityX_08_Ch3c.upk     *.upk.bak
copy CityX_08_ChQ1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_08_ChR79_LOD1.upk     *.upk.bak
copy CityX_09_Ch7c.upk     *.upk.bak
copy CityX_09_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityX_09_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityX_09_Cine_Ch5b_Drop_Off_Ivy_At_Botanical_Gardens.upk     *.upk.bak
copy CityX_09_Cine_Ch7b_Cloudburst_Activated.upk     *.upk.bak
copy CityX_09_Cine_Ch7c_BM_Returns_To_Ivy.upk     *.upk.bak
copy CityX_10_Ch1a.upk     *.upk.bak
copy CityX_10_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityX_10_ChR34579_LOD1.upk     *.upk.bak
copy CityX_10_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_10_Cine_Ch3cd_HeavyCannonDrop.upk     *.upk.bak
copy CityX_10_Static_LOD1.upk     *.upk.bak
copy CityX_11_Ch5b.upk     *.upk.bak
copy CityX_11_ChA1.upk     *.upk.bak
copy CityX_11_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityX_11_ChX1_Ch789_LOD1.upk     *.upk.bak
copy CityX_11_Cine_Ch5b_Releasing_Plant_1.upk     *.upk.bak
copy CityX_12_ChD1ab_Ch9.upk     *.upk.bak
copy CityX_12_ChR579_LOD1.upk     *.upk.bak
copy CityX_13_Ch3456789.upk     *.upk.bak
copy CityX_13_Ch3b.upk     *.upk.bak
copy CityX_13_ChR579_LOD1.upk     *.upk.bak
copy CityX_13_Cine_Final_Mech_Outro.upk     *.upk.bak
copy CityX_13_Cine_Leaves_Orphanage.upk     *.upk.bak
copy CityX_14_ChC5j.upk     *.upk.bak
copy CityX_14_ChD1ab_Ch56789.upk     *.upk.bak
copy CityX_14_ChX1a_Ch9_LOD1.upk     *.upk.bak
copy CityX_15_Cine_Ch7_Botanical_Gardens_Attack.upk     *.upk.bak
copy CityX_16_ChR579_LOD1.upk     *.upk.bak
copy CityX_16_Static_LOD1.upk     *.upk.bak
copy CityX_17_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityX_19_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityX_20.upk     *.upk.bak
copy CityX_20_Ch5.upk     *.upk.bak
copy CityX_20_Static_LOD1.upk     *.upk.bak
copy CityX_28.upk     *.upk.bak
copy CityX_28_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityX__Ch7_LOD2.upk     *.upk.bak
copy CityX__ChF478.upk     *.upk.bak
copy CityX__ChN2.upk     *.upk.bak
copy CityX_BankLarge_Outro_Cine.upk     *.upk.bak
copy CityX_L3.upk     *.upk.bak
copy CityX_L7.upk     *.upk.bak
copy CityX_L8.upk     *.upk.bak
copy CityX_T10_Ch3c.upk     *.upk.bak
copy CityX_T10_Cine_Ch3_AKAmbush.upk     *.upk.bak
copy CityX_T11_Ch3c.upk     *.upk.bak
copy CityX_U16_Ch3b.upk     *.upk.bak
copy CityX_U16_ChC2c.upk     *.upk.bak
copy CityY.upk     *.upk.bak
copy CityY_02.upk     *.upk.bak
copy CityY_02_Static_LOD1.upk     *.upk.bak
copy CityY_03_Airship1_Static_Ch4a_ChO0_LOD1.upk     *.upk.bak
copy CityY_03_Static_LOD1.upk     *.upk.bak
copy CityY_04.upk     *.upk.bak
copy CityY_04_ChC5m.upk     *.upk.bak
copy CityY_04_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityY_04_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityY_05.upk     *.upk.bak
copy CityY_05_Ch8.upk     *.upk.bak
copy CityY_05_ChD1ab_Ch789_LOD1.upk     *.upk.bak
copy CityY_05_ChQ1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_05_ChW1_Anim.upk     *.upk.bak
copy CityY_05_Static_LOD1.upk     *.upk.bak
copy CityY_06_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityY_07.upk     *.upk.bak
copy CityY_08.upk     *.upk.bak
copy CityY_08_Ch5c_LOD1.upk     *.upk.bak
copy CityY_08_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityY_08_ChX1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_08_Static_LOD1.upk     *.upk.bak
copy CityY_09.upk     *.upk.bak
copy CityY_09_Ch5c.upk     *.upk.bak
copy CityY_09_Ch5c_Cine_Control_Room_Breach.upk     *.upk.bak
copy CityY_09_Ch5c_Cine_ControlRoom_To_Batmobile.upk     *.upk.bak
copy CityY_09_Ch9a.upk     *.upk.bak
copy CityY_09_Ch9a_Cine_BM_Saves_Oracle.upk     *.upk.bak
copy CityY_09_Static_LOD1.upk     *.upk.bak
copy CityY_10.upk     *.upk.bak
copy CityY_10_Ch345_LOD1.upk     *.upk.bak
copy CityY_10_ChQ1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_10_ChX1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_10_Cine_Ch7c_Ivy_Plant_Tunnels.upk     *.upk.bak
copy CityY_12_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityY_13_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityY_13_ChR579_LOD1.upk     *.upk.bak
copy CityY_13_ChX1_Ch789_LOD1.upk     *.upk.bak
copy CityY_14_Ch345_LOD1.upk     *.upk.bak
copy CityY_14_ChP5.upk     *.upk.bak
copy CityY_14_ChQ1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_14_ChQ1_Ch789_LOD1.upk     *.upk.bak
copy CityY_15_ChX1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_16_ChA2.upk     *.upk.bak
copy CityY_16_ChD1ab_Ch9.upk     *.upk.bak
copy CityY_17_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityY_17_ChX1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_18_ChQ1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_18_ChX1_Ch3456789_LOD1.upk     *.upk.bak
copy CityY_19.upk     *.upk.bak
copy CityY_19_ChR79_LOD1.upk     *.upk.bak
copy CityY_19_Static_LOD1.upk     *.upk.bak
copy CityY__ChC5d.upk     *.upk.bak
copy CityY__ChF8.upk     *.upk.bak
copy CityY__ChN4.upk     *.upk.bak
copy CityY_L4.upk     *.upk.bak
copy CityY_S04.upk     *.upk.bak
copy CityY_U04_Ch456789_LOD1.upk     *.upk.bak
copy CityY_U09_Ch9a_Cine_Rooftop_Confrontation.upk     *.upk.bak
copy CityY_U09_ChX1a_Ch3456789_LOD1.upk     *.upk.bak
copy CityZ.upk     *.upk.bak
copy CityZ_00_Ch2.upk     *.upk.bak
copy CityZ_00_Ch3az.upk     *.upk.bak
copy CityZ_00_Cine_Ch2_Gordon_Bridge.upk     *.upk.bak
copy CityZ_01_ChR579_LOD1.upk     *.upk.bak
copy CityZ_01_Static_LOD1.upk     *.upk.bak
copy CityZ_02_ChR79_LOD1.upk     *.upk.bak
copy CityZ_03_Static_LOD1.upk     *.upk.bak
copy CityZ_04.upk     *.upk.bak
copy CityZ_04_ChR34579_LOD1.upk     *.upk.bak
copy CityZ_05_Ch7.upk     *.upk.bak
copy CityZ_05_ChC5f.upk     *.upk.bak
copy CityZ_06_ChX1_Ch56789_LOD1.upk     *.upk.bak
copy CityZ_07.upk     *.upk.bak
copy CityZ_07_Ch1bc_LOD1.upk     *.upk.bak
copy CityZ_07_Ch56789_Static.upk     *.upk.bak
copy CityZ_07_Ch5a.upk     *.upk.bak
copy CityZ_07_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityZ_07_ChR34579_LOD1.upk     *.upk.bak
copy CityZ_07_Cine_Ch1c_Penthouse_Rescue.upk     *.upk.bak
copy CityZ_07_Cine_Ch1c_Penthouse_Rescue_PT2.upk     *.upk.bak
copy CityZ_07_Cine_Ch5a_OR_Penthouse.upk     *.upk.bak
copy CityZ_07_Static_LOD1.upk     *.upk.bak
copy CityZ_08_Ch1c_LOD1.upk     *.upk.bak
copy CityZ_08_ChA3.upk     *.upk.bak
copy CityZ_08_ChC5c.upk     *.upk.bak
copy CityZ_08_ChD1ab_Ch789.upk     *.upk.bak
copy CityZ_08_ChX1_Ch789_LOD1.upk     *.upk.bak
copy CityZ_08_Cine_Ch1c_Batmobile_Intro.upk     *.upk.bak
copy CityZ_09_ChD1ab_Ch9.upk     *.upk.bak
copy CityZ_10.upk     *.upk.bak
copy CityZ_10_Ch2C.upk     *.upk.bak
copy CityZ_10_Ch6_Anim.upk     *.upk.bak
copy CityZ_10_ChC5g.upk     *.upk.bak
copy CityZ_10_Static_LOD1.upk     *.upk.bak
copy CityZ_12.upk     *.upk.bak
copy CityZ_12_Ch3a.upk     *.upk.bak
copy CityZ_12_Ch5b9a.upk     *.upk.bak
copy CityZ_12_Ch9a_LOD1.upk     *.upk.bak
copy CityZ_12_ChQ1_Ch9_LOD1.upk     *.upk.bak
copy CityZ_12_Static_LOD1.upk     *.upk.bak
copy CityZ_13.upk     *.upk.bak
copy CityZ_13_ChR579_LOD1.upk     *.upk.bak
copy CityZ_13_ChX1a_Ch9_LOD1.upk     *.upk.bak
copy CityZ_14.upk     *.upk.bak
copy CityZ_14_ChX1a_Ch9_LOD1.upk     *.upk.bak
copy CityZ_15_ChD1_Ch3456789_LOD1.upk     *.upk.bak
copy CityZ_15_ChR34579_LOD1.upk     *.upk.bak
copy CityZ_15_Static_LOD1.upk     *.upk.bak
copy CityZ_17.upk     *.upk.bak
copy CityZ_17_Ch123456_LOD1.upk     *.upk.bak
copy CityZ_17_Ch1b.upk     *.upk.bak
copy CityZ_17_Ch9bc.upk     *.upk.bak
copy CityZ_17_Ch9bck_Anim.upk     *.upk.bak
copy CityZ_17_ChB6.upk     *.upk.bak
copy CityZ_17_ChF478.upk     *.upk.bak
copy CityZ_17_Cine_Ch1b_Gordon_Rendezvous.upk     *.upk.bak
copy CityZ_17_Cine_Ch9k_BM_Batwing_Pickup.upk     *.upk.bak
copy CityZ_17_Cine_Ch9k_Sc_Lockup.upk     *.upk.bak
copy CityZ_17_Static_LOD1.upk     *.upk.bak
copy CityZ_18.upk     *.upk.bak
copy CityZ_18_Ch2.upk     *.upk.bak
copy CityZ_18_Cine_Ch2_Collect_Batsuit.upk     *.upk.bak
copy CityZ_18_Static_LOD1.upk     *.upk.bak
copy CityZ_19.upk     *.upk.bak
copy CityZ_19_ChD1ab_Ch3456789.upk     *.upk.bak
copy CityZ_19_ChR34579_LOD1.upk     *.upk.bak
copy CityZ_20.upk     *.upk.bak
copy CityZ__Ch6.upk     *.upk.bak
copy CityZ__ChF78.upk     *.upk.bak
copy CityZ__ChN3.upk     *.upk.bak
copy CityZ__Cine_Ch1b_ChV0_Transition_From_Intro.upk     *.upk.bak
copy CityZ_L10.upk     *.upk.bak
copy CityZ_L2.upk     *.upk.bak
copy CityZ_L6.upk     *.upk.bak
copy CityZ_S02_ChP45_LOD1.upk     *.upk.bak
copy CityZ_T01.upk     *.upk.bak
copy CityZ_T17.upk     *.upk.bak
copy CityZ_T17_Ch3a.upk     *.upk.bak
copy CityZ_T17_Ch5b.upk     *.upk.bak
copy CityZ_T17_Ch9b.upk     *.upk.bak
copy CityZ_T17_ChA5_Anim.upk     *.upk.bak
copy CityZ_T17_ChD1ab_Ch9_Anim.upk     *.upk.bak
copy CityZ_T17_ChG2_Anim.upk     *.upk.bak
copy CityZ_T17_ChW1_Anim.upk     *.upk.bak
copy CityZ_T17_Cine_Ch1c_Delivering_Ivy_GCPD.upk     *.upk.bak
copy CityZ_T17_Cine_Ch56789_TwoFace_Into_GCPD.upk     *.upk.bak
copy CityZ_T17_Cine_Ch5ab_GCPD_Get_Ivy.upk     *.upk.bak
copy CityZ_T17_Cine_Ch5c6789_Riddler_GCPD_Lockup.upk     *.upk.bak
copy CityZ_T17_Cine_Ch9ab_Oracle_At_GCPD.upk     *.upk.bak
copy CityZ_T17_Cine_ChP5_Penguin_Into_GCPD.upk     *.upk.bak
copy Clocktower.upk     *.upk.bak
copy Clocktower_C1_Ch1d2_ChV0.upk     *.upk.bak
copy Clocktower_C1_Ch34.upk     *.upk.bak
copy Clocktower_C1_Ch56789.upk     *.upk.bak
copy Clocktower_C1_ChA5.upk     *.upk.bak
copy Clocktower_C1_ChA5_Anim.upk     *.upk.bak
copy Clocktower_C1_Cine_Ch1_Clocktower_Meeting.upk     *.upk.bak
copy Clocktower_C1_Cine_Ch3_Clocktower_Gordon.upk     *.upk.bak
copy Clocktower_C1_Cine_Ch3a_Oracle_Apartment_Three_Wall.upk     *.upk.bak
copy Clocktower_C1_Trans.upk     *.upk.bak
copy Death_Alfred_FromStart.upk     *.upk.bak
copy Death_Deacon.upk     *.upk.bak
copy Death_DeathStroke_Beacon.upk     *.upk.bak
copy Death_DeathStroke_Checkpoint.upk     *.upk.bak
copy Death_DeathStroke_Watchtower.upk     *.upk.bak
copy Death_Firecrew.upk     *.upk.bak
copy Death_Firefly.upk     *.upk.bak
copy Death_Harley_BatmanKilled.upk     *.upk.bak
copy Death_Harley_RobinHostage.upk     *.upk.bak
copy Death_Harley_RobinKilled.upk     *.upk.bak
copy Death_Hush_BatmanKilled.upk     *.upk.bak
copy Death_Hush_LuciusKilled.upk     *.upk.bak
copy Death_Ivy_LeftArea.upk     *.upk.bak
copy Death_Joker_BatMobile.upk     *.upk.bak
copy Death_Joker_Boss.upk     *.upk.bak
copy Death_Joker_FromCh3.upk     *.upk.bak
copy Death_Joker_GordonEscort.upk     *.upk.bak
copy Death_Joker_LoseTruck.upk     *.upk.bak
copy Death_Knight_AfterReveal.upk     *.upk.bak
copy Death_Knight_APC.upk     *.upk.bak
copy Death_Knight_Beacon.upk     *.upk.bak
copy Death_Knight_Ch2ToCh8.upk     *.upk.bak
copy Death_Knight_ChaseFail.upk     *.upk.bak
copy Death_Knight_Checkpoint.upk     *.upk.bak
copy Death_Knight_LeftIvy.upk     *.upk.bak
copy Death_Knight_WatchTower.upk     *.upk.bak
copy Death_Penguin_CacheBatman.upk     *.upk.bak
copy Death_Penguin_CacheNightwing.upk     *.upk.bak
copy Death_Penguin_HostageNightwing.upk     *.upk.bak
copy Death_Pyg.upk     *.upk.bak
copy Death_Rid_Killed_Rioter.upk     *.upk.bak
copy Death_Riddler_Batman.upk     *.upk.bak
copy Death_Riddler_Catwoman.upk     *.upk.bak
copy Death_Riddler_WrongKey.upk     *.upk.bak
copy Death_Robin_UntilCh6.upk     *.upk.bak
copy Death_Scarecrow_ChaseFail.upk     *.upk.bak
copy Death_Scarecrow_FromStart.upk     *.upk.bak
copy Death_Scarecrow_LeftBeacon.upk     *.upk.bak
copy Death_Thug_BatMobile.upk     *.upk.bak
copy Death_TwoFace.upk     *.upk.bak
copy Death_TwoFace_Fail.upk     *.upk.bak
copy DLC_Anim_Nightwing_Ninja_Com_SF.upk     *.upk.bak
copy Film.upk     *.upk.bak
copy Film_A1.upk     *.upk.bak
copy Film_A1_Ch6.upk     *.upk.bak
copy Film_A1_Cine_Ch6_JK_Buisness_Intro.upk     *.upk.bak
copy Film_A2.upk     *.upk.bak
copy Film_A2_Ch6.upk     *.upk.bak
copy Film_A2_Ch6_Anim.upk     *.upk.bak
copy Film_B1.upk     *.upk.bak
copy Film_B1_Ch23.upk     *.upk.bak
copy Film_B1_Ch4.upk     *.upk.bak
copy Film_B1_Ch5.upk     *.upk.bak
copy Film_B1_Ch5_Anim.upk     *.upk.bak
copy Film_B1_Ch6.upk     *.upk.bak
copy Film_B1_Ch6789.upk     *.upk.bak
copy Film_B1_Ch678_Anim.upk     *.upk.bak
copy Film_B1_Ch6_Anim.upk     *.upk.bak
copy Film_B1_Ch9.upk     *.upk.bak
copy Film_B1_Ch9_Anim.upk     *.upk.bak
copy Film_B1_Cine_Ch23_Gordon_Flashback.upk     *.upk.bak
copy Film_B1_Cine_Ch6_3_JT_Flashback_3.upk     *.upk.bak
copy Film_B1_Cine_Ch6_Alpha_Reveal.upk     *.upk.bak
copy Film_B3_Ch6.upk     *.upk.bak
copy Film_B4.upk     *.upk.bak
copy Film_B4_Ch6.upk     *.upk.bak
copy Hideout.upk     *.upk.bak
copy Hideout__Ch8.upk     *.upk.bak
copy Hideout_A2.upk     *.upk.bak
copy Hideout_A2_Ch8.upk     *.upk.bak
copy Hideout_A3.upk     *.upk.bak
copy Hideout_A3_Ch8.upk     *.upk.bak
copy Hideout_A3_Ch9.upk     *.upk.bak
copy Hideout_A3_Cine_Ch8_Gord_Elev_Journey.upk     *.upk.bak
copy Hideout_A3_Cine_Ch8_Red_Hood_Part1.upk     *.upk.bak
copy Hideout_A3_Cine_Ch8_Red_Hood_Part2.upk     *.upk.bak
copy Hideout_B1.upk     *.upk.bak
copy Hideout_B1_Ch8.upk     *.upk.bak
copy Hideout_B2.upk     *.upk.bak
copy Hideout_B2_Ch8.upk     *.upk.bak
copy Hideout_B2_SideTunnels.upk     *.upk.bak
copy Hideout_L1.upk     *.upk.bak
copy INTRO_PT1.upk     *.upk.bak
copy Ivy.upk     *.upk.bak
copy Ivy_T01.upk     *.upk.bak
copy Ivy_T01_Ch7c.upk     *.upk.bak
copy Ivy_T02.upk     *.upk.bak
copy Ivy_T03_Ch7c.upk     *.upk.bak
copy JokerBoss.upk     *.upk.bak
copy JokerBoss_A2.upk     *.upk.bak
copy JokerBoss_B1.upk     *.upk.bak
copy JokerBoss_B1_Cine_Ch9o_Decowl.upk     *.upk.bak
copy JokerBoss_B1_Cine_Ch9r_PreEnd.upk     *.upk.bak
copy JokerBoss_B2_Ch9r.upk     *.upk.bak
copy JokerBoss_B2_Static_01.upk     *.upk.bak
copy JokerBoss_C1.upk     *.upk.bak
copy Lockup.upk     *.upk.bak
copy Lockup_B1.upk     *.upk.bak
copy Lockup_B1_Ch12.upk     *.upk.bak
copy Lockup_B1_Ch1bcd.upk     *.upk.bak
copy Lockup_B1_Ch5_Anim.upk     *.upk.bak
copy Lockup_B1_Ch7c8.upk     *.upk.bak
copy Lockup_B1_Ch9.upk     *.upk.bak
copy Lockup_B1_Ch9_Anim.upk     *.upk.bak
copy Lockup_B1_ChG2.upk     *.upk.bak
copy Lockup_B1_ChG2_Ch9b.upk     *.upk.bak
copy Lockup_B1_ChW1_Ch9b.upk     *.upk.bak
copy Lockup_B1_Cine_Ch1_Delivering_Ivy_GCPD.upk     *.upk.bak
copy Lockup_B1_Cine_Ch5_GCPD_Get_Ivy.upk     *.upk.bak
copy Lockup_B1_Cine_Ch5c6789_Delivering_Riddler_GCPD.upk     *.upk.bak
copy Lockup_B1_Cine_Ch9_Oracle_At_GCPD.upk     *.upk.bak
copy Lockup_B1_Cine_ChN4_ManBat_Lockup.upk     *.upk.bak
copy Lockup_C1.upk     *.upk.bak
copy Lockup_C1_Ch1bcd.upk     *.upk.bak
copy Lockup_C1_Ch9bc.upk     *.upk.bak
copy Lockup_C1_Cine_Ch1_Delivering_Ivy_GCPD.upk     *.upk.bak
copy Lockup_C1_Cine_Ch56789_Delivering_TwoFace_GCPD.upk     *.upk.bak
copy Lockup_C1_Cine_ChP5_Delivering_Penguin_GCPD.upk     *.upk.bak
copy Main_Bmob_Bm_Cant_Leave_A_SF.upk     *.upk.bak
copy Main_Bulletproof_Bm_Thoughts_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch01_Sus_Veh_Fail_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch01_Sus_Veh_Inter_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch01_Sus_Veh_Lockin_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch02_Ace_Ex_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Apc_Fail_Driv_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Apc_Fail_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Apc_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Crime_Scene_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Gord_Getin_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Gord_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch03_Peng_Chase_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch04_Stagg_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch05_Ht_Mw_Lock_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch05_Ivy_Plant_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch06_Film_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch07_No_Car_A_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch07_No_Car_B_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch07_Protect_Ivy_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch08_Hideout_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch09_Gcpd_Att_Car_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch09_Gcpd_Att_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch09_Ora_Car_SF.upk     *.upk.bak
copy Main_Bulletproof_Mp_Ch09_Ora_Mw_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Bf_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Ds_Bm_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Ds_Gn_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Peng_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Pyg_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Rid_Cw_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Rid_Or_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Tf_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Vr_SF.upk     *.upk.bak
copy Main_Bulletproof_Mw_Wt_SF.upk     *.upk.bak
copy Main_Cash_Aerial_Cityx_SF.upk     *.upk.bak
copy Main_Cash_Aerial_Cityy_Ch3_Onward_SF.upk     *.upk.bak
copy Main_Cash_Aerial_Cityy_Ch7_After_Fear_Toxin_SF.upk     *.upk.bak
copy Main_Cash_Aerial_Cityy_Ch7_During_Fear_Toxin_SF.upk     *.upk.bak
copy Main_Cash_Aerial_Cityz_Ch5_Onward_SF.upk     *.upk.bak
copy Main_Ch01_Out_Of_Bounds_A_SF.upk     *.upk.bak
copy Main_Ch01_Out_Of_Bounds_B_SF.upk     *.upk.bak
copy Main_Ch01_Out_Of_Bounds_SF.upk     *.upk.bak
copy Main_Ch02_S01_Ace_Ext_Find_Workers_Split_SF.upk     *.upk.bak
copy Main_Ch03_Out_Of_Bounds_SF.upk     *.upk.bak
copy Main_Ch03_S01_Cityz_G_Escort_Fail_SF.upk     *.upk.bak
copy Main_Ch03_S20_Cityx_Bm_Thought_Interrogate_Split_SF.upk     *.upk.bak
copy Main_Ch05_Out_Of_Bounds_SF.upk     *.upk.bak
copy Main_Ch05_S22_Bm_Thought_Remote_Bmob_B_SF.upk     *.upk.bak
copy Main_Ch05_S22_Bm_Thought_Remote_Bmob_SF.upk     *.upk.bak
copy Main_Ch07_Jk_Gas_Grapple_SF.upk     *.upk.bak
copy Main_Ch07_Out_Of_Bounds_SF.upk     *.upk.bak
copy Main_Ch09_Out_Of_Bounds_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Azrael_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Deathstroke_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Firechief_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Penguin_Ride_Knightfall_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Penguin_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Pyg_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Riddler_Ride_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Two_Face_Ride_Alt_SF.upk     *.upk.bak
copy Main_Gcpd_Lock_Up_Two_Face_Ride_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_H_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_I_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_J_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_K_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_L_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_M_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_N_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_O_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_P_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch03_Q_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_H_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_I_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_J_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch05_K_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_H_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_I_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_J_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_K_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_L_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_M_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_N_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_O_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_P_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch07_Q_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_H_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_I_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_J_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_K_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_L_SF.upk     *.upk.bak
copy Main_Jk_Roof_Ch09_M_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Apc_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Apc_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Apc_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Apc_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Azrael_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Azrael_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Azrael_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Bomb_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Bomb_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Bomb_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Bomb_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Deacon_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Deacon_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Done_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firecrew_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firefly_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firefly_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firefly_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firefly_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Firefly_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Hush_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Manbat_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Manbat_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Manbat_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Manbat_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Penguin_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Pyg_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Pyg_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Pyg_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Pyg_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_D_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_E_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_F_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_G_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_H_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_I_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_J_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Riddler_K_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Twoface_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Twoface_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Twoface_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Watchtower_A_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Watchtower_B_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Watchtower_C_SF.upk     *.upk.bak
copy Main_Jk_Roof_Mw_Watchtower_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Noapcnospacedrones_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Noapctimelimitkilled_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Noapctimelimitlost_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Reselect_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_5_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_6_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_7_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_8_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Apc_Spawn_9_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Ar_Wheel_Intro_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_All_Done_H_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_All_Done_I_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight1radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight2radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight3radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Fight4radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Azrael_Suspend_Tankscan_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bank_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Blackfire_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Blackfire_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch1_Sus_Driver_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch2_Ace_Esc_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch2_Ace_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Apc_Drv_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Apc_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Batwing_Upgrade_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Gordon_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Gordon_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch3_Truck_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch4_Stagg_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch5_Cobra_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch5_Ivy_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch5_Missile_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch5_Scan_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch6_Film_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch7_Gas_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch7_Ivy_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch8_Hideout_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch9_Gcpd_Att_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Ch9_Oracle_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Gcpd_Return_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Bank_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Black_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Black_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Command_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Death_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Hush_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Orphan_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Peng_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Pyg_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Rid_Cave_Alt_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Rid_Cave_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Bp_Side_Rid_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_E_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_H_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_I_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_J_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_K_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_L_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_M_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_N_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_O_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_P_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Pre_Ds_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Pre_Ds_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Q_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Remaining_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Remaining_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Remaining_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_S_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Drones_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Feargas_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_0_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_10_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_10radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_11_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_11radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_12_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_12radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_13_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_13radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_14_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_14radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_15_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_1radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_2radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_3radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_4radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_5_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_5radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_6_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_6radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_7_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_7radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_8_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_8radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_9_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Firecrew_9radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Q_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firecrews_Tut_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_B_Intel_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_C_Intel_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_D_Intel_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Firefly_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Full_Knightfall_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Gcpd_Attack_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Hush_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Hush_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch1a_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch3a_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch3b_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch3c_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch5a_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch5b_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch5c_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch7a_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch7b_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch9a_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mainpath_Ch9b_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_D_Intel_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_E_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_F_Intel_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Manbat_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Mid_Knightfall_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_E_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_H_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_I_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_J_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_K_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_L_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_M_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_N_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_O_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_P_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Q_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_R_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Remaining_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Remaining_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Remaining_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_T_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Militia_U_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Cache2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Cache3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Cache4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Cache5_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_K_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Suspend_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Suspend_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Suspend_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_X1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_X2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_X3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_Z1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_Z2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Penguin_Van_Z3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene1radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene3radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene4radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene5_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene5radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene6_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Crimescene6radius_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_L_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_M_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Search_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Search_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Search_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Search_4_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Search_5_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Pyg_Tut_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_Alt_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_B_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_E_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_H_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_I_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_J_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_K_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_L_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_M_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_P_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_Q_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Riddler_Tut_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_A_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_All_Done_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_C_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_D_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_E_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_F_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_G_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_H_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_I_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_J_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_K_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_L_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_M_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_N_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_O_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_P_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Q_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_R_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Remaining_1_Alt_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Remaining_1_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Remaining_2_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Remaining_3_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_S_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Search_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_Suspend_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_T_SF.upk     *.upk.bak
copy Main_Miss_Wheel_Watchtowers_U_SF.upk     *.upk.bak
copy ManBat_B1.upk     *.upk.bak
copy Orphan.upk     *.upk.bak
copy Orphan_01.upk     *.upk.bak
copy Orphan_04.upk     *.upk.bak
copy Orphan_09.upk     *.upk.bak
copy Orphan_15.upk     *.upk.bak
copy Orphan_A1.upk     *.upk.bak
copy Orphan_C1.upk     *.upk.bak
copy Orphan_C2.upk     *.upk.bak
copy Orphan_C3.upk     *.upk.bak
copy Orphan_C4.upk     *.upk.bak
copy Orphan_C6.upk     *.upk.bak
copy Orphan_C6_ChC0.upk     *.upk.bak
copy Orphan_C6_ChC4z.upk     *.upk.bak
copy Orphan_C7.upk     *.upk.bak
copy Orphan_C7_ChC0.upk     *.upk.bak
copy Orphan_C7_ChC4y.upk     *.upk.bak
copy Orphan_C8_ChC0.upk     *.upk.bak
copy Orphan_C8_ChC4w.upk     *.upk.bak
copy PenguinCache.upk     *.upk.bak
copy PenguinCache_B3.upk     *.upk.bak
copy PenguinCache_C1.upk     *.upk.bak
copy PenguinCache_C2_ChP2345_LOD1.upk     *.upk.bak
copy PenguinCache_C3.upk     *.upk.bak
copy PenguinCache_C3_ChP345_LOD1.upk     *.upk.bak
copy PenguinCache_C4_ChP45.upk     *.upk.bak
copy PenguinCache_C5.upk     *.upk.bak
copy PenguinCache_C5_ChP5.upk     *.upk.bak
copy Playable_Batmobile_SF.upk     *.upk.bak
copy Playable_BatmobileFunhouse_SF.upk     *.upk.bak
copy Playable_BatmobileJoker_SF.upk     *.upk.bak
copy Playable_BatmobileMK2_SF.upk     *.upk.bak
copy Playable_Catwoman0_SF.upk     *.upk.bak
copy Playable_Catwoman_SF.upk     *.upk.bak
copy Playable_Gordon_SF.upk     *.upk.bak
copy Playable_Joker_SF.upk     *.upk.bak
copy Playable_JokerFPS_SF.upk     *.upk.bak
copy Playable_Nightwing0_SF.upk     *.upk.bak
copy Playable_Nightwing_SF.upk     *.upk.bak
copy Playable_Robin0_SF.upk     *.upk.bak
copy Playable_Robin_SF.upk     *.upk.bak
copy Pyg.upk     *.upk.bak
copy Pyg_B1.upk     *.upk.bak
copy Pyg_B1_Cine_Pyg_Intro.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_110_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_130_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_140_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_150_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_160_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_180_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_205_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_70_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_80_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Collected_90_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_One_Hundred_Solved_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_05_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_10_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_15_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_20_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_25_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Percent_50_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_01_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_02_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_03_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_04_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_05_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_06_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_07_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_08_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_09_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_10_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_25_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_50_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Remaining_75_SF.upk     *.upk.bak
copy Riddler_City_Trophy_Progression_Solved_All_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Demo_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Eight_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Eleven_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fifteen_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fightback_Five_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fightback_Four_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fightback_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fightback_Three_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fightback_Two_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Final_One_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_First_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Five_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Four_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Fourteen_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Nine_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_One_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Seven_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Six_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Ten_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Thirteen_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Three_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Twelve_SF.upk     *.upk.bak
copy Riddler_Inf_Inf_Two_SF.upk     *.upk.bak
copy Riddler_New_Riddles_Chapter_1_SF.upk     *.upk.bak
copy Riddler_New_Riddles_Chapter_3_SF.upk     *.upk.bak
copy Riddler_New_Riddles_Chapter_5_SF.upk     *.upk.bak
copy Riddler_New_Riddles_Chapter_7_SF.upk     *.upk.bak
copy Riddler_New_Riddles_Chapter_9_SF.upk     *.upk.bak
copy Riddler_New_Riddles_First_Grid_Square_SF.upk     *.upk.bak
copy Sacrifice_C1.upk     *.upk.bak
copy Sacrifice_C1_Ch9.upk     *.upk.bak
copy Scenes_Gauntlet_Alfred_Ch10_Kfall_Kfall_End_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Alfred_Ch10_Kfall_Mid_Kf_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Alfred_Penguin_Cache_4_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Ds_Reveal_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Final_Showdown_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_One_Branch_Complete_Beacons_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_One_Branch_Complete_Checkpoints_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_One_Branch_Complete_Towers_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Three_Branches_Done_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Two_Branches_Beacons_Left_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Two_Branches_Checkpoints_Left_SF.upk     *.upk.bak
copy Scenes_Gauntlet_Deathstroke_Progress_Two_Branches_Towers_Left_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Billboard_16_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Billboard_16_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Billboard_16_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Billboard_17_Billboard_17_Alt_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Billboard_18_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_1_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_1_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_1_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_2_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_2_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_2_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_3_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_3_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_3_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_4_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_4_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_4_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_5_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_5_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_5_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_6_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_6_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Cave_6_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Bleake_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Bleake_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Film_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Film_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Founders_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Founders_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_D_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_E_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_F_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_G_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_H_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_I_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_J_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_K_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Generic_L_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Hideout_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Hideout_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Miagani_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Miagani_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Pre_Mech_2_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Stagg_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Chapter_09_Reminders_Stagg_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Got_Rec_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Got_Rec_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Got_Rec_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_1_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_1_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_1_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_2_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_2_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_2_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_3_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_3_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_3_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_4_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_4_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Orphan_4_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Rec_Hints_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Rec_Hints_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Billboard_Teases_Rec_Hints_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Bomb_Rioter_Reminder_A_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Bomb_Rioter_Reminder_B_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Bomb_Rioter_Reminder_C_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Bomb_Rioter_Reminder_D_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Bomb_Rioter_Reminder_E_SF.upk     *.upk.bak
copy Scenes_Tv_Riddler_Hub_Post_Game_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_A_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_B_Os_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_B_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_C_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_D_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_E_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_F_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_G_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_H_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_I_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_J_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_K_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_L_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_M_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_N_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_O_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_P_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_Q_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_R_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_T_SF.upk     *.upk.bak
copy Side_Checkpoint_Chkpnt_U_SF.upk     *.upk.bak
copy Side_Checkpoint_Remaining_1_SF.upk     *.upk.bak
copy Side_Checkpoint_Remaining_2_SF.upk     *.upk.bak
copy Side_Checkpoint_Remaining_3_SF.upk     *.upk.bak
copy Side_Checkpoint_Rh_First_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_5_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_5_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_A_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_A_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_C_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_C_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_D_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_D_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_E_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_E_Intr_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_F_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_F_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_G_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_G_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_H_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_H_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_I_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_I_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_J_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_J_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_K_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_K_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_L_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_L_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_M_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_M_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_N_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_N_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_O_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_O_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_P_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_P_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_Q_Done_SF.upk     *.upk.bak
copy Side_Deathstroke_Beacon_Q_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Bm_Thought_Car_SF.upk     *.upk.bak
copy Side_Deathstroke_Can_Use_Winch_SF.upk     *.upk.bak
copy Side_Deathstroke_Cant_Eject_A_SF.upk     *.upk.bak
copy Side_Deathstroke_Cant_Eject_SF.upk     *.upk.bak
copy Side_Deathstroke_Cant_Shoot_SF.upk     *.upk.bak
copy Side_Deathstroke_Checkpoints_Cant_Shoot_SF.upk     *.upk.bak
copy Side_Deathstroke_Checkpoints_Commander_SF.upk     *.upk.bak
copy Side_Deathstroke_Checkpoints_Destroy_Control_SF.upk     *.upk.bak
copy Side_Deathstroke_Core_Exposed_Turn_Back_SF.upk     *.upk.bak
copy Side_Deathstroke_No_Car_SF.upk     *.upk.bak
copy Side_Deathstroke_Player_Gone_Too_Far_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Post_Reveal_Bomb_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Post_Reveal_Chckpnt_Last_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Post_Reveal_Chckpnt_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Post_Reveal_Taunts_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_Bm_Takes_Beacon_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_Bm_Takes_Cp_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_Bm_Takes_Tower_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_Bombs_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_SF.upk     *.upk.bak
copy Side_Deathstroke_Progress_Pre_Reveal_Taunts_Wtwr_SF.upk     *.upk.bak
copy Side_Deathstroke_Remaining_1_SF.upk     *.upk.bak
copy Side_Deathstroke_Remaining_2_SF.upk     *.upk.bak
copy Side_Deathstroke_Remaining_3_SF.upk     *.upk.bak
copy Side_Deathstroke_Seq_Ds_Lock_Up_SF.upk     *.upk.bak
copy Side_Deathstroke_Tankbattle_Intro_SF.upk     *.upk.bak
copy Side_Deathstroke_Tankbattle_Taunts_SF.upk     *.upk.bak
copy Side_Deathstroke_Voice_Synth_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_10_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Bm_Wait_Here_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_11_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_12_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_13_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_14_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Rescue_Alt_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_15_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Bm_Wait_Here_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_16_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Bm_Thought_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_1_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_2_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Bm_Wait_Here_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_3_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_4_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_5_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_6_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Bm_Wait_Here_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_7_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_8_Thug_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Beating_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Dont_Leave_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Fireman_Help_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Fireman_Os_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Rescue_Fl_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Rescue_SF.upk     *.upk.bak
copy Side_Firecrew_Part_9_Thug_Os_SF.upk     *.upk.bak
copy Side_Penguin_Bm_Nw_Enter_Cache_B_SF.upk     *.upk.bak
copy Side_Penguin_Bm_Nw_Enter_Cache_C_SF.upk     *.upk.bak
copy Side_Penguin_Bm_Nw_Enter_Cache_D_SF.upk     *.upk.bak
copy Side_Penguin_Cache_2_Peng_Thug_Open_Truck_SF.upk     *.upk.bak
copy Side_Penguin_Cache_3_Peng_Thug_Open_Truck_SF.upk     *.upk.bak
copy Side_Penguin_Cache_4_Peng_Thug_Open_Truck_SF.upk     *.upk.bak
copy Side_Penguin_Peng_Truck_See_Batmobile_A_SF.upk     *.upk.bak
copy Side_Penguin_Peng_Truck_See_Batmobile_B_SF.upk     *.upk.bak
copy Side_Penguin_Peng_Truck_See_Batmobile_C_SF.upk     *.upk.bak
copy Side_Penguin_Peng_Truck_See_Batmobile_D_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Car_Barrier_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Gun_Broke_One_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Gun_Broke_Three_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Gun_Broke_Two_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Lights_Out_One_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Lights_Out_Three_SF.upk     *.upk.bak
copy Side_Watchtower_Militia_Lights_Out_Two_SF.upk     *.upk.bak
copy Side_Watchtower_Remaining_1_SF.upk     *.upk.bak
copy Side_Watchtower_Remaining_2_SF.upk     *.upk.bak
copy Side_Watchtower_Remaining_3_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_A_Bm_Leaves_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_A_Bm_Near_Door_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_A_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_B_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_C_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_D_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_E_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_F_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_G_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_H_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_I_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_J_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_K_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_L_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_M_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_N_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_O_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_P_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_Q_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_R_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_S_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_T_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_U_SF.upk     *.upk.bak
copy Side_Watchtower_Tower_V_SF.upk     *.upk.bak
copy Stagg.upk     *.upk.bak
copy Stagg_A1.upk     *.upk.bak
copy Stagg_A1_Ch4.upk     *.upk.bak
copy Stagg_A1_Ch4_Anim.upk     *.upk.bak
copy Stagg_A1_Ch7.upk     *.upk.bak
copy Stagg_A2.upk     *.upk.bak
copy Stagg_A2_Ch4.upk     *.upk.bak
copy Stagg_A2_Ch7.upk     *.upk.bak
copy Stagg_B1.upk     *.upk.bak
copy Stagg_B1_Ch4.upk     *.upk.bak
copy Stagg_B1_Static_Ch1234ab.upk     *.upk.bak
copy Stagg_B1_Static_Ch4c56789.upk     *.upk.bak
copy Stagg_B2.upk     *.upk.bak
copy Stagg_B2_Ch4.upk     *.upk.bak
copy Stagg_B2_Ch6789.upk     *.upk.bak
copy Stagg_B3.upk     *.upk.bak
copy Stagg_B3_Ch45a.upk     *.upk.bak
copy Stagg_B3_Ch7.upk     *.upk.bak
copy Stagg_B3_Cine_Ch45a_Cloudburst_Stolen.upk     *.upk.bak
copy Stagg_C1.upk     *.upk.bak
copy Stagg_C1_Ch4.upk     *.upk.bak
copy Stagg_C1_Static_Lod1.upk     *.upk.bak
copy Startup.upk     *.upk.bak
copy StartupPatch.upk     *.upk.bak
copy UnderAce.upk     *.upk.bak
copy UnderAce_A3_Ch23.upk     *.upk.bak
copy UnderAce_A4.upk     *.upk.bak
copy UnderAce_A4_Ch23.upk     *.upk.bak
copy UnderAce_A4_Cine_Ch2_Mixing_Room.upk     *.upk.bak
copy UnderAce_B3_Ch23.upk     *.upk.bak
copy WayneTower_B1.upk     *.upk.bak
copy WayneTower_B1_Ch3.upk     *.upk.bak
copy WayneTower_B1_Cine_ChH2_Batman_Meets_Hush.upk *.upk.bak